apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteMany

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost-deployment
  labels:
    app: mattermost
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mattermost
  template:
    metadata:
      labels:
        app: mattermost
    spec:
      containers:
        - name: mattermost
          #image: mattermost/mattermost-enterprise-edition:6.1
          image: mattermost/mattermost-prod-app
          ports:
            - containerPort: 8065          
          volumeMounts:
          - name: mattermost-data
            mountPath: /mattermost/data
          envFrom:
            - prefix:
              configMapRef:
                name: mattermost-config
          env:
          - name: MM_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: MMUSER_PASSWORD
          livenessProbe:
            exec:
              command:
              # if MM_STATUS is not OK sh returns exit code 1
              - /bin/sh
              - -c
              - MM_STATUS=`curl -s http://localhost:8000/api/v4/system/ping | jq -r ".status"` && [ "$MM_STATUS" = "OK" ]
              # other option:
              #- curl -f http://localhost:8000/api/v4/system/ping || exit 1
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
      volumes:
      - name: mattermost-data
        persistentVolumeClaim:
          claimName: mattermost-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mattermost-service
spec:
  type: NodePort
  selector:
    app: mattermost
  ports:
  - protocol: TCP
    port: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mattermost-ingress
  annotations:
    # from mattermost documentation
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
spec:
  tls:
  - hosts:
      - mm-test.525.su
    secretName: mattermost-tls
  rules:
  - host: mm-test.525.su
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mattermost-service
            port:
              number: 8000
