apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.1
          ports:
            - containerPort: 5432          
          volumeMounts:
          - name: postgres-init-script-vol
            mountPath: /docker-entrypoint-initdb.d/postgres_init.sh            
            subPath: postgres_init.sh
          - name: postgres-init-script-vol
            mountPath: /tmp/postgres_init.sql
            subPath: postgres_init.sql
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
          envFrom:
          - prefix:
            configMapRef:
              name: mattermost-config
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          - name: MMUSER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: MMUSER_PASSWORD
      volumes:
      - name: postgres-init-script-vol
        configMap:
          name: postgres-init-script
          items:
          - key: postgres_init.sh
            path: postgres_init.sh
          - key: postgres_init.sql
            path: postgres_init.sql
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
